name: MLflow Workflow

on:
  push:
    branches:
      - main

jobs:
  mlflow_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run MLflow script
        run: |
          python Pointure_GaussianNB.ipynb
          # Ecrire le CML rapport
          echo "## Metriques:" >> rapport.md
          cat metrics.txt >> rapport.md

      - name: Commit rapport
        run: |
          git config --global user.name 'MicheleDLS'
          git config --global user.email 'MicheleDLS@users.noreply.github.com'
          #git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add rapport.md metrics.txt modele.txt
          git commit -am "sauvegarde des rapport"
          git push
