name: Modele Workflow
on: [push]
permissions:
  contents: write
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: WORKFLOW
        run: |
          #Upgrade pip
          /usr/bin/python3 -m pip install --upgrade pip
          # Installe environnement
          pip install -r requirements.txt
          # Cree le dossier output
          mkdir -p output
          # Exécuter le script
          timestamp=$(date +"%Y%m%d_%H%M")
          python Pointure_GaussianNB.ipynb
          ls -R
          echo "Current directory: $(pwd)"
          cd /github/workspace
          pwd #
          ls -R
          # Ecrire le rapport
          # Utiliser le timestamp pour le rapport
          rapport="output/rapport_${timestamp}.md"
          echo "## Metriques:" >> ${rapport}
          cat metrics_file >> ${rapport}
          echo "## Modele:" >> ${rapport}
          cat modele_file >> ${rapport}
          # Commit sur git 
          git config --global user.name 'MicheleDLS'
          git config --global user.email 'MicheleDLS@users.noreply.github.com'
          git add ${rapport} metrics_file modele_file
          git commit -m "sauvegarde des rapports"
          git pull --rebase origin
          git push origin HEAD
