name: Modele Workflow
on: [push]
permissions:
  contents: write
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: WORKFLOW
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Upgrade pip
          python -m pip install --upgrade pip
          # Installe environnement
          pip install -r requirements.txt
          # Exécuter le script
          python Pointure_GaussianNB.ipynb
          # Ecrire le rapport
          echo "## Metriques:" >> rapport.md
          cat metrics.txt >> rapport.md
          echo "## Modele:" >> rapport.md
          cat modele.txt >> rapport.md
          # Commit sur git 
          git config --global user.name 'MicheleDLS'
          git config --global user.email 'MicheleDLS@users.noreply.github.com'
          git add rapport.md metrics.txt modele.txt
          git commit -m "sauvegarde des rapports"
          git pull --rebase origin
          git push origin HEAD
