name: Modele Workflow
on: [push]
permissions:
  contents: write
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: WORKFLOW
        run: |
          # Installe environnement
          pip install -r requirements.txt
          # Cree le dossier output
          mkdir -p output
          # Exécuter le script Python et obtenir le timestamp
          timestamp=$(date +"%Y%m%d_%H%M")
          python Pointure_GaussianNB.ipynb
          # Ecrire le rapport
          # Utiliser le timestamp pour le rapport
          rapport="output/rapport_${timestamp}.md"
          echo "## Metriques:" >> ${rapport}
          cat ${metrics_file} >> ${rapport}
          echo "## Modele:" >> ${rapport}
          cat ${modele_file} >> ${rapport}
          # Commit sur git 
          git config --global user.name 'MicheleDLS'
          git config --global user.email 'MicheleDLS@users.noreply.github.com'
          git add ${rapport} ${metrics_file} ${modele_file}
          git commit -m "sauvegarde des rapports"
          git pull --rebase origin
          git push origin HEAD
